In [1]:
# dependencies
import pandas as pd

In [3]:
# import csv
raw_data = pd.read_csv("Red_Light_Camera_Violations.csv")
raw_data.head()

,INTERSECTION,CAMERA ID,ADDRESS,VIOLATION DATE,VIOLATIONS,X COORDINATE,Y COORDINATE,LATITUDE,LONGITUDE,LOCATION,Historical Wards 2003-2015,Zip Codes,Community Areas,Census Tracts,Wards
0,IRVING PARK AND KILPATRICK,2763.0,4700 W IRVING PARK ROA,04/09/2015,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,VAN BUREN AND WESTERN,2054.0,2400 W VAN BUREN STREE,04/14/2015,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,115TH AND HALSTED,2552.0,11500 S HALSTED STREE,04/08/2015,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,IRVING PARK AND KILPATRICK,2764.0,4700 W IRVING PARK ROA,04/19/2015,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ELSTON AND IRVING PARK,1503.0,3700 W IRVING PARK ROA,04/23/2015,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
# filter for blanks, nulls
data_clean_columns = raw_data[["INTERSECTION", "CAMERA ID", "ADDRESS", "VIOLATION DATE", "VIOLATIONS", "LATITUDE", "LONGITUDE", "Zip Codes"]].dropna()
data_clean_columns

,INTERSECTION,CAMERA ID,ADDRESS,VIOLATION DATE,VIOLATIONS,LATITUDE,LONGITUDE,Zip Codes
7,4700 WESTERN,2141.0,4700 S WESTERN AVENUE,06/05/2019,3,41.808378,-87.684571,22248.0
9,WESTERN AND DEVON,1211.0,6400 N WESTERN AVENUE,06/05/2019,2,41.997818,-87.690033,4450.0
13,CICERO AND ADDISON,1612.0,3600 N CICERO AVENUE,06/05/2019,7,41.946164,-87.747215,22618.0
15,LAKE SHORE DR AND BELMONT,1413.0,400 W BELMONT AVE,06/05/2019,75,41.940241,-87.639639,4449.0
18,SACRAMENTO AND CHICAGO,1814.0,3000 W CHICAGO AVENUE,06/05/2019,8,41.895705,-87.702219,21560.0
...,...,...,...,...,...,...,...,...
885743,KEDZIE AND 31ST,2134.0,3200 W 31ST STREET,08/30/2023,9,41.837339,-87.704951,21569.0
885744,ELSTON AND LAWRENCE,1284.0,4440 W LAWRENCE AVENUE,08/30/2023,12,41.968226,-87.739599,21869.0
885745,PULASKI AND CHICAGO,1982.0,800 N PULASKI ROAD,08/30/2023,2,41.895456,-87.726231,4299.0
885746,MADISON AND WESTERN,1934.0,2400 W MADISON,08/30/2023,1,41.881271,-87.686536,21184.0
885747,CENTRAL AND DIVERSEY,1642.0,2800 N CENTRAL AVENUE,08/31/2023,1,41.931366,-87.766397,22615.0

In [ ]:
# group by: camera id and month / year, etc.

In [ ]:
#